# Start job trigger (local)
GET http://localhost:7071/api/StartWeatherJobTrigger

###

# Get job images (local)
GET http://localhost:7071/api/images/48742c7b-64c3-46a6-8188-0e343447c011

###

# Start job trigger (Azure)
GET https://server-side-assignment.azurewebsites.net/api/startweatherjobtrigger

###

# Get job images (Azure) (test)
GET https://server-side-assignment.azurewebsites.net/api/images/3953908a-203d-4425-803d-787887a496c8